jwltay/fonylancer

- Gemfile.lock
- app/models/bid.rb
- app/models/job.rb
- app/models/user.rb
Added validations for Job, Bid and User models.
> Adds validations for models

- Gemfile.lock
- app/controllers/jobs_controller.rb
- config/routes.rb
- test/controllers/jobs_controller_test.rb
Created pages and jobs controller and routes.
> [WIP] Controllers and pages for Jobs

- app/controllers/bids_controller.rb
- app/controllers/users_controller.rb
- test/controllers/bids_controller_test.rb
- test/controllers/users_controller_test.rb
Added controllers for Bid and User models with their relevant CRUD methods.
> Controllers

- Gemfile
- Gemfile.lock
- app/policies/application_policy.rb
> added pundit gem in gemfile

- Gemfile.lock
- app/models/bid.rb
- app/models/job.rb
- app/views/jobs/index.html.erb
- app/views/jobs/show.html.erb
Updated bid and job models to reflect user types more accurately. Respective views' instance variables have also been updated.
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] I have performed a self-review of my code
> Model update user

- app/models/job.rb
- db/seeds.rb
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
> 23 add seeds for all models

- app/assets/stylesheets/components/_freelancers.scss
- app/assets/stylesheets/components/_index.scss
- app/views/users/index.html.erb
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
> Browse freelancers

- .browserslistrc
- .gitignore
- Gemfile
- Gemfile.lock
- babel.config.js
- bin/webpack
- bin/webpack-dev-server
- config/webpack/development.js
- config/webpack/environment.js
- config/webpack/production.js
- config/webpack/test.js
- config/webpacker.yml
- package.json
- postcss.config.js
- yarn.lock
Fixing webpack to deploy on heroku
> reinstalled webpacker

- Gemfile
Hopefully this works i dunno anything anymore
> Add webpacker gem

- Gemfile
- Gemfile.lock
- app/views/pages/home.html.erb
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
> updated gemfile (again)

- Gemfile
- Gemfile.lock
> Revert "Styled frontend for freelancers index page"

- Gemfile.lock
added support for heroku in gemfile.lock
> add platform x86-64-linux

- Gemfile.lock
This PR adds the missing Gemfile.lock changes from the previous commit
N/A
> Update missing gemfile.lock changes to linux platform

- Gemfile.lock
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_white_card.scss
- app/views/devise/registrations/new.html.erb
Added css to sign up form and centered it
> Css for sign up page

- app/assets/stylesheets/components/_secondary_navbar.scss
- app/javascript/controllers/profilebar_controller.js
- app/views/users/show.html.erb
Fixed profile bar's appearing and disappearing, changed margins to better fit Freelancer
> Edit profile bar

- app/controllers/jobs_controller.rb
- app/views/jobs/index.html.erb
> 20 as a visitor i can browse jobs frontend

- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/jobs/index.html.erb
1. added location and placeholder in app/views/devise/registrations/new.html.erb and in application controller added permit:location
> Updated sign up page for location with street address, city and country code in placeholder

- app/views/jobs/index.html.erb
1.Added bid button 
2. Added drop down
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my code
> Final Css for job index page

- app/assets/stylesheets/components/_black_header.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_white-box.scss
- app/assets/stylesheets/config/_fonts.scss
- app/controllers/jobs_controller.rb
- app/models/job.rb
- app/views/jobs/show.html.erb
- app/views/users/show.html.erb
- db/seeds.rb
Added user show page with appropriate styling. Made necessary changes in jobs controller and job model. Changed font of entire app to better match Freelancer.
> 55 as a user i can view an individual job post

- db/seeds.rb
Made seeds for users and jobs have longer descriptions
> changed seeds for user and job to have longer descriptions

- app/assets/stylesheets/components/_secondary_navbar.scss
- app/views/layouts/application.html.erb
- app/views/shared/_secondary_navbar.html.erb
Edited secondary navbar to align with all pages containers
Added fake links to replicate original website pop up link cards when hovered over navbar buttons
> 58 fix container for secondary nav bar

- app/controllers/bids_controller.rb
- app/controllers/jobs_controller.rb
- app/views/jobs/show.html.erb
- app/views/shared/_bid_form.html.erb
Created a bid form partial that renders in job show view. Edited new and create action in bids controller to pass data around.
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added proof(eg. screenshots) that prove my fix is effective or that my feature works
> 62 as a freelancer i can bid for jobs with a specified rate backend

- app/assets/stylesheets/components/_white_card.scss
- app/views/devise/registrations/new.html.erb
- app/views/jobs/index.html.erb
- app/views/jobs/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_secondary_navbar.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
All links are routing correctly now
- Navbars rendered only at necessary pages
- Sign up form removed navbar and centered
- Sign up form changed into home page link
> 38 check all links working

- app/controllers/bids_controller.rb
- app/policies/bid_policy.rb
Bid policy has been edited so that logged in user can sumbit new bids
> 88 check pundit when creating bids and when marking jobs as complete

- app/views/jobs/show.html.erb
Job's bid index was not appearing. Cleaned up code and fixed some basic styling/nesting. Current Bids section only visible by job poster. Included a comment to show where future additions should be placed.
> Fix job's bid index view

- app/views/jobs/index.html.erb
- app/views/jobs/show.html.erb
Styled job index to look more like Freelancer.
> 86 job index page style

- app/views/users/index.html.erb
Made minor changes to user index so that it looks more like Freelancer
> minor styling changes to user index

- app/views/jobs/show.html.erb
Fixed extra render of bid form at the bottom of the job show page.
> removed extra render of bid form
